# AI 2024 Online Summer Internship
### Name: Rasikh Ali
### Email: rasikhali1234@gmail.com

## System & Libraries
<div class="alert alert-block alert-success">
    Using <b>Python </b> v3.8.18
    <br>
    with <b>Jupyter </b> v7.4.9
</div>
<div class="alert alert-block alert-info">
    
|    Libarries    | Version |     Purpose     |
|-----------------|---------|-----------------|
|Pandas           | v1.4.2  | Used for Data Manipulation and Analysis | 
|Numpy            | v1.23.5 | Used for Array Manipulation             |
|Pickle           | v4.0    | Used for Saving and Loading Model       |
|LabelEncoder     |         | Used for Encoding Categorical Features  |
|SVM              |         | Classifier for Classification, Regression, Outlier Detection  |
|Accuracy_Score   |         | Used for Calculating Accuracy Score of a Model                |
|Train_Test_Split |         | Used for Splitting array/matrices into train,test subsets     |
    
</div>

In [1]:
import pandas as pd
import numpy as np
import pickle

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

C:\Users\ABC\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\ABC\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\ABC\anaconda3\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

## Loading Dataset

In [2]:
sample_data = pd.read_csv('dataset/train.csv')
sample_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Understanding Dataset

<div class="alert alert-block alert-info">
About <b>Dataset</b>.

| Attributes | Description  |
|------------|--------------|
|passengerId | Passenger's Id (in dataset, irrelevant)                        |
|survived    | Passenger Survival (0/1 = NotSurvived/Survived)                |
|pclass      | Passenger's Ticket class (Upper, Middle, Lower = 0, 1, 2)      |
|sex         | Passenger's Gender (male, female)                              |
|age         | Passenger's Age                                                |
|sibsp       | # of Siblings / Spouses onboard                                |
|parch       | # of Parents / Children onboard                                |
|ticket      | Passenger's Ticket Number                                      |
|fare        | Passenger's Fare                                               |
|cabin       | Passenger's Cabin Number                                       |
|embarked    | Port of Embarkation (C,Q,S = Cherbourgh,Queenstown,Southampton)|
    
</div>

In [3]:
print("-- Attributes in Sample Data --")
for cols in sample_data.columns:
    print(cols)

-- Attributes in Sample Data --
PassengerId
Survived
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Cabin
Embarked

In [4]:
print("-- Number of instances in Sample Data --")
print(sample_data.count())

-- Number of instances in Sample Data --
PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [5]:
print("-- Number of Unique Values in Sample Data --")
print(sample_data.nunique())

-- Number of Unique Values in Sample Data --
PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [6]:
print("-- Number of Null Values in Sample Data --")
print(sample_data.isnull().sum())

-- Number of Null Values in Sample Data --
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
print("-- Insights of Sample Data --")
sample_data.info()

-- Insights of Sample Data --
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## Pre-Processing

#### Managing Null Values

<div class="alert alert-block alert-success">
    As the Attribute: Age is <b>Numerical</b> and not Categorical, We'll use Median (Average), Also convert it into int
</div>

In [8]:
sample_data['Age'] = sample_data['Age'].fillna(sample_data['Age'].median())

In [9]:
sample_data['Age'] = sample_data['Age'].astype('int')

In [10]:
print("-- No More Null Values in Age --")
print(sample_data.isnull().sum())

-- No More Null Values in Age --
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

<div class="alert alert-block alert-success">
    As the Attribute: Embarked is <b>Textual</b> and Categorical, We'll use Mode (Most Frequent)
</div>

In [11]:
sample_data['Embarked'] = sample_data['Embarked'].fillna(sample_data['Embarked'].mode()[0])

In [12]:
print("-- No More Null Values in Embarked --")
print(sample_data.isnull().sum())

-- No More Null Values in Embarked --
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

<div class="alert alert-block alert-danger">
More than <b>50%</b> of Cabin's values are Null, so we'll drop that column 
</div>

In [13]:
sample_data = sample_data.drop(columns=['Cabin'], axis=1)
sample_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,S

<div class="alert alert-block alert-danger">
Also dropping <b>Irrelevant</b> Columns
</div>

In [14]:
sample_data = sample_data.drop(columns=['PassengerId', 'Ticket', 'Fare', 'Name'], axis=1)
sample_data.head()

   Survived  Pclass     Sex  Age  SibSp  Parch Embarked
0         0       3    male   22      1      0        S
1         1       1  female   38      1      0        C
2         1       3  female   26      0      0        S
3         1       1  female   35      1      0        S
4         0       3    male   35      0      0        S

## Label Encoding

<div class="alert alert-block alert-success">
    As the Attributes: <b>Sex</b> and <b>Embarked</b> is Textual, We'll Need to Encode it as Scikit-learn only understands data in Numerical Representation
    <br>
    Output (Survived) is already in Numerical
</div>

In [15]:
print("-- Unique Values in Attribute: Sex --")
print(sample_data.Sex.unique())

-- Unique Values in Attribute: Sex --
['male' 'female']

In [16]:
print("-- Unique Values in Attribute: Embarked --")
print(sample_data.Embarked.unique())

-- Unique Values in Attribute: Embarked --
['S' 'C' 'Q']

In [17]:
# Labels
sex = pd.DataFrame({'Sex':['male', 'female']})
embarked = pd.DataFrame({'Embarked':['S', 'C', 'Q']})


# Initializing Label Encoders
sex_label_encoder = LabelEncoder()
embarked_label_encoder = LabelEncoder()

# Training Label Encoder
sex_label_encoder.fit(np.ravel(sex))
embarked_label_encoder.fit(np.ravel(embarked))

LabelEncoder()

In [18]:
sample_data_encoded = sample_data.copy()
sample_data_encoded_original = sample_data.copy()

In [19]:
# Transform Input Attributes into Numerical Representation
sample_data_encoded['Sex'] = sex_label_encoder.transform(sample_data['Sex']) 
sample_data_encoded['Embarked'] = embarked_label_encoder.transform(sample_data['Embarked'])

In [20]:
# All the Attributes are Numerical 
sample_data_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    int32
 3   Age       891 non-null    int32
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Embarked  891 non-null    int32
dtypes: int32(3), int64(4)
memory usage: 38.4 KB

In [21]:
# Save the Transformed Features into CSV File 
sample_data_encoded.to_csv(r'sample-data-encoded.csv', index = False, header = True)

## Training Phase

#### Splitting data into train/test

<div class="alert alert-block alert-info">
    Splitting data into train-test: Training = <b>80%</b> and Testing = <b>20%</b>.
</div>

In [22]:
training_data, testing_data = train_test_split(sample_data_encoded, test_size=0.2, random_state=0, shuffle=False)

In [23]:
# Save the train and test data into CSV files
training_data.to_csv(r'training-data.csv', index = False, header = True)
testing_data.to_csv(r'testing-data.csv', index = False, header = True)

In [24]:
# Printing Training Data
print("-- Training Data --")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(training_data)

-- Training Data --
     Survived  Pclass  Sex  Age  SibSp  Parch  Embarked
0           0       3    1   22      1      0         2
1           1       1    0   38      1      0         0
2           1       3    0   26      0      0         2
3           1       1    0   35      1      0         2
4           0       3    1   35      0      0         2
5           0       3    1   28      0      0         1
6           0       1    1   54      0      0         2
7           0       3    1    2      3      1         2
8           1       3    0   27      0      2         2
9           1       2    0   14      1      0         0
10          1       3    0    4      1      1         2
11          1       1    0   58      0      0         2
12          0       3    1   20      0      0         2
13          0       3    1   39      1      5         2
14          0       3    0   14      0      0         2
15          1       2    0   55      0      0         2
16          0       3    1    2      4      1         1
17          1       2    1   28      0      0         2
18          0       3    0   31      1      0         2
19          1       3    0   28      0      0         0
20          0       2    1   35      0      0         2
21          1       2    1   34      0      0         2
22          1       3    0   15      0      0         1
23          1       1    1   28      0      0         2
24          0       3    0    8      3      1         2
25          1       3    0   38      1      5         2
26          0       3    1   28      0      0         0
27          0       1    1   19      3      2         2
28          1       3    0   28      0      0         1
29          0       3    1   28      0      0         2
30          0       1    1   40      0      0         0
31          1       1    0   28      1      0         0
32          1       3    0   28      0      0         1
33          0       2    1   66      0      0         2
34          0       1    1   28      1      0         0
35          0       1    1   42      1      0         2
36          1       3    1   28      0      0         0
37          0       3    1   21      0      0         2
38          0       3    0   18      2      0         2
39          1       3    0   14      1      0         0
40          0       3    0   40      1      0         2
41          0       2    0   27      1      0         2
42          0       3    1   28      0      0         0
43          1       2    0    3      1      2         0
44          1       3    0   19      0      0         1
45          0       3    1   28      0      0         2
46          0       3    1   28      1      0         1
47          1       3    0   28      0      0         1
48          0       3    1   28      2      0         0
49          0       3    0   18      1      0         2
50          0       3    1    7      4      1         2
51          0       3    1   21      0      0         2
52          1       1    0   49      1      0         0
53          1       2    0   29      1      0         2
54          0       1    1   65      0      1         0
55          1       1    1   28      0      0         2
56          1       2    0   21      0      0         2
57          0       3    1   28      0      0         0
58          1       2    0    5      1      2         2
59          0       3    1   11      5      2         2
60          0       3    1   22      0      0         0
61          1       1    0   38      0      0         2
62          0       1    1   45      1      0         2
63          0       3    1    4      3      2         2
64          0       1    1   28      0      0         0
65          1       3    1   28      1      1         0
66          1       2    0   29      0      0         2
67          0       3    1   19      0      0         2
68          1       3    0   17      4      2         2
69          0       3    1   26      2      0         2
70          0       2    1   32      0      0         2
71          0       3    0   16      5      2         2
72          0       2    1   21      0      0         2
73          0       3    1   26      1      0         0
74          1       3    1   32      0      0         2
75          0       3    1   25      0      0         2
76          0       3    1   28      0      0         2
77          0       3    1   28      0      0         2
78          1       2    1    0      0      2         2
79          1       3    0   30      0      0         2
80          0       3    1   22      0      0         2
81          1       3    1   29      0      0         2
82          1       3    0   28      0      0         1
83          0       1    1   28      0      0         2
84          1       2    0   17      0      0         2
85          1       3    0   33      3      0         2
86          0       3    1   16      1      3         2
87          0       3    1   28      0      0         2
88          1       1    0   23      3      2         2
89          0       3    1   24      0      0         2
90          0       3    1   29      0      0         2
91          0       3    1   20      0      0         2
92          0       1    1   46      1      0         2
93          0       3    1   26      1      2         2
94          0       3    1   59      0      0         2
95          0       3    1   28      0      0         2
96          0       1    1   71      0      0         0
97          1       1    1   23      0      1         0
98          1       2    0   34      0      1         2
99          0       2    1   34      1      0         2
100         0       3    0   28      0      0         2
101         0       3    1   28      0      0         2
102         0       1    1   21      0      1         2
103         0       3    1   33      0      0         2
104         0       3    1   37      2      0         2
105         0       3    1   28      0      0         2
106         1       3    0   21      0      0         2
107         1       3    1   28      0      0         2
108         0       3    1   38      0      0         2
109         1       3    0   28      1      0         1
110         0       1    1   47      0      0         2
111         0       3    0   14      1      0         0
112         0       3    1   22      0      0         2
113         0       3    0   20      1      0         2
114         0       3    0   17      0      0         0
115         0       3    1   21      0      0         2
116         0       3    1   70      0      0         1
117         0       2    1   29      1      0         2
118         0       1    1   24      0      1         0
119         0       3    0    2      4      2         2
120         0       2    1   21      2      0         2
121         0       3    1   28      0      0         2
122         0       2    1   32      1      0         0
123         1       2    0   32      0      0         2
124         0       1    1   54      0      1         2
125         1       3    1   12      1      0         0
126         0       3    1   28      0      0         1
127         1       3    1   24      0      0         2
128         1       3    0   28      1      1         0
129         0       3    1   45      0      0         2
130         0       3    1   33      0      0         0
131         0       3    1   20      0      0         2
132         0       3    0   47      1      0         2
133         1       2    0   29      1      0         2
134         0       2    1   25      0      0         2
135         0       2    1   23      0      0         0
136         1       1    0   19      0      2         2
137         0       1    1   37      1      0         2
138         0       3    1   16      0      0         2
139         0       1    1   24      0      0         0
140         0       3    0   28      0      2         0
141         1       3    0   22      0      0         2
142         1       3    0   24      1      0         2
143         0       3    1   19      0      0         1
144         0       2    1   18      0      0         2
145         0       2    1   19      1      1         2
146         1       3    1   27      0      0         2
147         0       3    0    9      2      2         2
148         0       2    1   36      0      2         2
149         0       2    1   42      0      0         2
150         0       2    1   51      0      0         2
151         1       1    0   22      1      0         2
152         0       3    1   55      0      0         2
153         0       3    1   40      0      2         2
154         0       3    1   28      0      0         2
155         0       1    1   51      0      1         0
156         1       3    0   16      0      0         1
157         0       3    1   30      0      0         2
158         0       3    1   28      0      0         2
159         0       3    1   28      8      2         2
160         0       3    1   44      0      1         2
161         1       2    0   40      0      0         2
162         0       3    1   26      0      0         2
163         0       3    1   17      0      0         2
164         0       3    1    1      4      1         2
165         1       3    1    9      0      2         2
166         1       1    0   28      0      1         2
167         0       3    0   45      1      4         2
168         0       1    1   28      0      0         2
169         0       3    1   28      0      0         2
170         0       1    1   61      0      0         2
171         0       3    1    4      4      1         1
172         1       3    0    1      1      1         2
173         0       3    1   21      0      0         2
174         0       1    1   56      0      0         0
175         0       3    1   18      1      1         2
176         0       3    1   28      3      1         2
177         0       1    0   50      0      0         0
178         0       2    1   30      0      0         2
179         0       3    1   36      0      0         2
180         0       3    0   28      8      2         2
181         0       2    1   28      0      0         0
182         0       3    1    9      4      2         2
183         1       2    1    1      2      1         2
184         1       3    0    4      0      2         2
185         0       1    1   28      0      0         2
186         1       3    0   28      1      0         1
187         1       1    1   45      0      0         2
188         0       3    1   40      1      1         1
189         0       3    1   36      0      0         2
190         1       2    0   32      0      0         2
191         0       2    1   19      0      0         2
192         1       3    0   19      1      0         2
193         1       2    1    3      1      1         2
194         1       1    0   44      0      0         0
195         1       1    0   58      0      0         0
196         0       3    1   28      0      0         1
197         0       3    1   42      0      1         2
198         1       3    0   28      0      0         1
199         0       2    0   24      0      0         2
200         0       3    1   28      0      0         2
201         0       3    1   28      8      2         2
202         0       3    1   34      0      0         2
203         0       3    1   45      0      0         0
204         1       3    1   18      0      0         2
205         0       3    0    2      0      1         2
206         0       3    1   32      1      0         2
207         1       3    1   26      0      0         0
208         1       3    0   16      0      0         1
209         1       1    1   40      0      0         0
210         0       3    1   24      0      0         2
211         1       2    0   35      0      0         2
212         0       3    1   22      0      0         2
213         0       2    1   30      0      0         2
214         0       3    1   28      1      0         1
215         1       1    0   31      1      0         0
216         1       3    0   27      0      0         2
217         0       2    1   42      1      0         2
218         1       1    0   32      0      0         0
219         0       2    1   30      0      0         2
220         1       3    1   16      0      0         2
221         0       2    1   27      0      0         2
222         0       3    1   51      0      0         2
223         0       3    1   28      0      0         2
224         1       1    1   38      1      0         2
225         0       3    1   22      0      0         2
226         1       2    1   19      0      0         2
227         0       3    1   20      0      0         2
228         0       2    1   18      0      0         2
229         0       3    0   28      3      1         2
230         1       1    0   35      1      0         2
231         0       3    1   29      0      0         2
232         0       2    1   59      0      0         2
233         1       3    0    5      4      2         2
234         0       2    1   24      0      0         2
235         0       3    0   28      0      0         2
236         0       2    1   44      1      0         2
237         1       2    0    8      0      2         2
238         0       2    1   19      0      0         2
239         0       2    1   33      0      0         2
240         0       3    0   28      1      0         0
241         1       3    0   28      1      0         1
242         0       2    1   29      0      0         2
243         0       3    1   22      0      0         2
244         0       3    1   30      0      0         0
245         0       1    1   44      2      0         1
246         0       3    0   25      0      0         2
247         1       2    0   24      0      2         2
248         1       1    1   37      1      1         2
249         0       2    1   54      1      0         2
250         0       3    1   28      0      0         2
251         0       3    0   29      1      1         2
252         0       1    1   62      0      0         2
253         0       3    1   30      1      0         2
254         0       3    0   41      0      2         2
255         1       3    0   29      0      2         0
256         1       1    0   28      0      0         0
257         1       1    0   30      0      0         2
258         1       1    0   35      0      0         0
259         1       2    0   50      0      1         2
260         0       3    1   28      0      0         1
261         1       3    1    3      4      2         2
262         0       1    1   52      1      1         2
263         0       1    1   40      0      0         2
264         0       3    0   28      0      0         1
265         0       2    1   36      0      0         2
266         0       3    1   16      4      1         2
267         1       3    1   25      1      0         2
268         1       1    0   58      0      1         2
269         1       1    0   35      0      0         2
270         0       1    1   28      0      0         2
271         1       3    1   25      0      0         2
272         1       2    0   41      0      1         2
273         0       1    1   37      0      1         0
274         1       3    0   28      0      0         1
275         1       1    0   63      1      0         2
276         0       3    0   45      0      0         2
277         0       2    1   28      0      0         2
278         0       3    1    7      4      1         1
279         1       3    0   35      1      1         2
280         0       3    1   65      0      0         1
281         0       3    1   28      0      0         2
282         0       3    1   16      0      0         2
283         1       3    1   19      0      0         2
284         0       1    1   28      0      0         2
285         0       3    1   33      0      0         0
286         1       3    1   30      0      0         2
287         0       3    1   22      0      0         2
288         1       2    1   42      0      0         2
289         1       3    0   22      0      0         1
290         1       1    0   26      0      0         2
291         1       1    0   19      1      0         0
292         0       2    1   36      0      0         0
293         0       3    0   24      0      0         2
294         0       3    1   24      0      0         2
295         0       1    1   28      0      0         0
296         0       3    1   23      0      0         0
297         0       1    0    2      1      2         2
298         1       1    1   28      0      0         2
299         1       1    0   50      0      1         0
300         1       3    0   28      0      0         1
301         1       3    1   28      2      0         1
302         0       3    1   19      0      0         2
303         1       2    0   28      0      0         1
304         0       3    1   28      0      0         2
305         1       1    1    0      1      2         2
306         1       1    0   28      0      0         0
307         1       1    0   17      1      0         0
308         0       2    1   30      1      0         0
309         1       1    0   30      0      0         0
310         1       1    0   24      0      0         0
311         1       1    0   18      2      2         0
312         0       2    0   26      1      1         2
313         0       3    1   28      0      0         2
314         0       2    1   43      1      1         2
315         1       3    0   26      0      0         2
316         1       2    0   24      1      0         2
317         0       2    1   54      0      0         2
318         1       1    0   31      0      2         2
319         1       1    0   40      1      1         0
320         0       3    1   22      0      0         2
321         0       3    1   27      0      0         2
322         1       2    0   30      0      0         1
323         1       2    0   22      1      1         2
324         0       3    1   28      8      2         2
325         1       1    0   36      0      0         0
326         0       3    1   61      0      0         2
327         1       2    0   36      0      0         2
328         1       3    0   31      1      1         2
329         1       1    0   16      0      1         0
330         1       3    0   28      2      0         1
331         0       1    1   45      0      0         2
332         0       1    1   38      0      1         2
333         0       3    1   16      2      0         2
334         1       1    0   28      1      0         2
335         0       3    1   28      0      0         2
336         0       1    1   29      1      0         2
337         1       1    0   41      0      0         0
338         1       3    1   45      0      0         2
339         0       1    1   45      0      0         2
340         1       2    1    2      1      1         2
341         1       1    0   24      3      2         2
342         0       2    1   28      0      0         2
343         0       2    1   25      0      0         2
344         0       2    1   36      0      0         2
345         1       2    0   24      0      0         2
346         1       2    0   40      0      0         2
347         1       3    0   28      1      0         2
348         1       3    1    3      1      1         2
349         0       3    1   42      0      0         2
350         0       3    1   23      0      0         2
351         0       1    1   28      0      0         2
352         0       3    1   15      1      1         0
353         0       3    1   25      1      0         2
354         0       3    1   28      0      0         0

In [25]:
# Printing Testing Data
print("-- Testing Data --")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(testing_data)

-- Testing Data --
     Survived  Pclass  Sex  Age  SibSp  Parch  Embarked
712         1       1    1   48      1      0         2
713         0       3    1   29      0      0         2
714         0       2    1   52      0      0         2
715         0       3    1   19      0      0         2
716         1       1    0   38      0      0         0
717         1       2    0   27      0      0         2
718         0       3    1   28      0      0         1
719         0       3    1   33      0      0         2
720         1       2    0    6      0      1         2
721         0       3    1   17      1      0         2
722         0       2    1   34      0      0         2
723         0       2    1   50      0      0         2
724         1       1    1   27      1      0         2
725         0       3    1   20      0      0         2
726         1       2    0   30      3      0         2
727         1       3    0   28      0      0         1
728         0       2    1   25      1      0         2
729         0       3    0   25      1      0         2
730         1       1    0   29      0      0         2
731         0       3    1   11      0      0         0
732         0       2    1   28      0      0         2
733         0       2    1   23      0      0         2
734         0       2    1   23      0      0         2
735         0       3    1   28      0      0         2
736         0       3    0   48      1      3         2
737         1       1    1   35      0      0         0
738         0       3    1   28      0      0         2
739         0       3    1   28      0      0         2
740         1       1    1   28      0      0         2
741         0       1    1   36      1      0         2
742         1       1    0   21      2      2         0
743         0       3    1   24      1      0         2
744         1       3    1   31      0      0         2
745         0       1    1   70      1      1         2
746         0       3    1   16      1      1         2
747         1       2    0   30      0      0         2
748         0       1    1   19      1      0         2
749         0       3    1   31      0      0         1
750         1       2    0    4      1      1         2
751         1       3    1    6      0      1         2
752         0       3    1   33      0      0         2
753         0       3    1   23      0      0         2
754         1       2    0   48      1      2         2
755         1       2    1    0      1      1         2
756         0       3    1   28      0      0         2
757         0       2    1   18      0      0         2
758         0       3    1   34      0      0         2
759         1       1    0   33      0      0         2
760         0       3    1   28      0      0         2
761         0       3    1   41      0      0         2
762         1       3    1   20      0      0         0
763         1       1    0   36      1      2         2
764         0       3    1   16      0      0         2
765         1       1    0   51      1      0         2
766         0       1    1   28      0      0         0
767         0       3    0   30      0      0         1
768         0       3    1   28      1      0         1
769         0       3    1   32      0      0         2
770         0       3    1   24      0      0         2
771         0       3    1   48      0      0         2
772         0       2    0   57      0      0         2
773         0       3    1   28      0      0         0
774         1       2    0   54      1      3         2
775         0       3    1   18      0      0         2
776         0       3    1   28      0      0         1
777         1       3    0    5      0      0         2
778         0       3    1   28      0      0         1
779         1       1    0   43      0      1         2
780         1       3    0   13      0      0         0
781         1       1    0   17      1      0         2
782         0       1    1   29      0      0         2
783         0       3    1   28      1      2         2
784         0       3    1   25      0      0         2
785         0       3    1   25      0      0         2
786         1       3    0   18      0      0         2
787         0       3    1    8      4      1         1
788         1       3    1    1      1      2         2
789         0       1    1   46      0      0         0
790         0       3    1   28      0      0         1
791         0       2    1   16      0      0         2
792         0       3    0   28      8      2         2
793         0       1    1   28      0      0         0
794         0       3    1   25      0      0         2
795         0       2    1   39      0      0         2
796         1       1    0   49      0      0         2
797         1       3    0   31      0      0         2
798         0       3    1   30      0      0         0
799         0       3    0   30      1      1         2
800         0       2    1   34      0      0         2
801         1       2    0   31      1      1         2
802         1       1    1   11      1      2         2
803         1       3    1    0      0      1         0
804         1       3    1   27      0      0         2
805         0       3    1   31      0      0         2
806         0       1    1   39      0      0         2
807         0       3    0   18      0      0         2
808         0       2    1   39      0      0         2
809         1       1    0   33      1      0         2
810         0       3    1   26      0      0         2
811         0       3    1   39      0      0         2
812         0       2    1   35      0      0         2
813         0       3    0    6      4      2         2
814         0       3    1   30      0      0         2
815         0       1    1   28      0      0         2
816         0       3    0   23      0      0         2
817         0       2    1   31      1      1         0
818         0       3    1   43      0      0         2
819         0       3    1   10      3      2         2
820         1       1    0   52      1      1         2
821         1       3    1   27      0      0         2
822         0       1    1   38      0      0         2
823         1       3    0   27      0      1         2
824         0       3    1    2      4      1         2
825         0       3    1   28      0      0         1
826         0       3    1   28      0      0         2
827         1       2    1    1      0      2         0
828         1       3    1   28      0      0         1
829         1       1    0   62      0      0         2
830         1       3    0   15      1      0         0
831         1       2    1    0      1      1         2
832         0       3    1   28      0      0         0
833         0       3    1   23      0      0         2
834         0       3    1   18      0      0         2
835         1       1    0   39      1      1         0
836         0       3    1   21      0      0         2
837         0       3    1   28      0      0         2
838         1       3    1   32      0      0         2
839         1       1    1   28      0      0         0
840         0       3    1   20      0      0         2
841         0       2    1   16      0      0         2
842         1       1    0   30      0      0         0
843         0       3    1   34      0      0         0
844         0       3    1   17      0      0         2
845         0       3    1   42      0      0         2
846         0       3    1   28      8      2         2
847         0       3    1   35      0      0         0
848         0       2    1   28      0      1         2
849         1       1    0   28      1      0         0
850         0       3    1    4      4      2         2
851         0       3    1   74      0      0         2
852         0       3    0    9      1      1         0
853         1       1    0   16      0      1         2
854         0       2    0   44      1      0         2
855         1       3    0   18      0      1         2
856         1       1    0   45      1      1         2
857         1       1    1   51      0      0         2
858         1       3    0   24      0      3         0
859         0       3    1   28      0      0         0
860         0       3    1   41      2      0         2
861         0       2    1   21      1      0         2
862         1       1    0   48      0      0         2
863         0       3    0   28      8      2         2
864         0       2    1   24      0      0         2
865         1       2    0   42      0      0         2
866         1       2    0   27      1      0         0
867         0       1    1   31      0      0         2
868         0       3    1   28      0      0         2
869         1       3    1    4      1      1         2
870         0       3    1   26      0      0         2
871         1       1    0   47      1      1         2
872         0       1    1   33      0      0         2
873         0       3    1   47      0      0         2
874         1       2    0   28      1      0         0
875         1       3    0   15      0      0         0
876         0       3    1   20      0      0         2
877         0       3    1   19      0      0         2
878         0       3    1   28      0      0         2
879         1       1    0   56      0      1         0
880         1       2    0   25      0      1         2
881         0       3    1   33      0      0         2
882         0       3    0   22      0      0         2
883         0       2    1   28      0      0         2
884         0       3    1   25      0      0         2
885         0       3    0   39      0      5         1
886         0       2    1   27      0      0         2
887         1       1    0   19      0      0         2
888         0       3    0   28      1      2         2
889         1       1    1   26      0      0         0
890         0       3    1   32      0      0         1

#### Splitting Input Vector and Output of Training Data

<div class="alert alert-block alert-info">
    Splitting <b>Input (x)</b> Vector and <b>Output (y)</b> of Training Data.
</div>

In [26]:
train_x = training_data.iloc[:, 1:]
train_x.head()

   Pclass  Sex  Age  SibSp  Parch  Embarked
0       3    1   22      1      0         2
1       1    0   38      1      0         0
2       3    0   26      0      0         2
3       1    0   35      1      0         2
4       3    1   35      0      0         2

In [27]:
train_y = training_data.iloc[:, 0]
train_y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

#### Training Model Using Support Vector Classifier

In [28]:
print("-- Training using SVC on Training Data --")
print("-- Parameters & Values: ", end='')

model_svc = SVC(gamma='auto', random_state=0)
model_svc.fit(train_x, np.ravel(train_y))

print(model_svc)

-- Training using SVC on Training Data --
-- Parameters & Values: SVC(gamma='auto', random_state=0)

In [29]:
# Saving Trained Model
pickle.dump(model_svc, open('model_svc.pkl', 'wb'))

## Testing Phase

#### Splitting Input Vector and Output of Testing Data

<div class="alert alert-block alert-info">
    Splitting <b>Input (x)</b> Vector and <b>Output (y)</b> of Testing Data.
</div>

In [30]:
test_x = testing_data.iloc[:, 1:]
test_x.head()

     Pclass  Sex  Age  SibSp  Parch  Embarked
712       1    1   48      1      0         2
713       3    1   29      0      0         2
714       2    1   52      0      0         2
715       3    1   19      0      0         2
716       1    0   38      0      0         0

In [31]:
test_y = testing_data.iloc[:, 0]
test_y.head()

712    1
713    0
714    0
715    0
716    1
Name: Survived, dtype: int64

#### Loading Model

In [32]:
# Load saved Model
model = pickle.load(open('model_svc.pkl', 'rb'))

#### Evaluating Model

In [33]:
model_predictions = model.predict(test_x)

testing_data_prediction = testing_data.copy(deep=True)
pd.options.mode.chained_assignment = None

testing_data_prediction['Prediction'] = model_predictions

In [34]:
# Printing Testing Data
print("-- Testing Data with Prediction --")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(testing_data_prediction)

-- Testing Data with Prediction --
     Survived  Pclass  Sex  Age  SibSp  Parch  Embarked  Prediction
712         1       1    1   48      1      0         2           0
713         0       3    1   29      0      0         2           0
714         0       2    1   52      0      0         2           0
715         0       3    1   19      0      0         2           0
716         1       1    0   38      0      0         0           1
717         1       2    0   27      0      0         2           1
718         0       3    1   28      0      0         1           0
719         0       3    1   33      0      0         2           0
720         1       2    0    6      0      1         2           1
721         0       3    1   17      1      0         2           0
722         0       2    1   34      0      0         2           0
723         0       2    1   50      0      0         2           0
724         1       1    1   27      1      0         2           0
725         0       3    1   20      0      0         2           0
726         1       2    0   30      3      0         2           0
727         1       3    0   28      0      0         1           1
728         0       2    1   25      1      0         2           0
729         0       3    0   25      1      0         2           1
730         1       1    0   29      0      0         2           1
731         0       3    1   11      0      0         0           1
732         0       2    1   28      0      0         2           0
733         0       2    1   23      0      0         2           0
734         0       2    1   23      0      0         2           0
735         0       3    1   28      0      0         2           0
736         0       3    0   48      1      3         2           0
737         1       1    1   35      0      0         0           1
738         0       3    1   28      0      0         2           0
739         0       3    1   28      0      0         2           0
740         1       1    1   28      0      0         2           0
741         0       1    1   36      1      0         2           1
742         1       1    0   21      2      2         0           1
743         0       3    1   24      1      0         2           0
744         1       3    1   31      0      0         2           0
745         0       1    1   70      1      1         2           0
746         0       3    1   16      1      1         2           0
747         1       2    0   30      0      0         2           1
748         0       1    1   19      1      0         2           0
749         0       3    1   31      0      0         1           0
750         1       2    0    4      1      1         2           1
751         1       3    1    6      0      1         2           1
752         0       3    1   33      0      0         2           0
753         0       3    1   23      0      0         2           0
754         1       2    0   48      1      2         2           0
755         1       2    1    0      1      1         2           1
756         0       3    1   28      0      0         2           0
757         0       2    1   18      0      0         2           0
758         0       3    1   34      0      0         2           0
759         1       1    0   33      0      0         2           1
760         0       3    1   28      0      0         2           0
761         0       3    1   41      0      0         2           0
762         1       3    1   20      0      0         0           0
763         1       1    0   36      1      2         2           1
764         0       3    1   16      0      0         2           0
765         1       1    0   51      1      0         2           1
766         0       1    1   28      0      0         0           0
767         0       3    0   30      0      0         1           1
768         0       3    1   28      1      0         1           0
769         0       3    1   32      0      0         2           0
770         0       3    1   24      0      0         2           0
771         0       3    1   48      0      0         2           0
772         0       2    0   57      0      0         2           0
773         0       3    1   28      0      0         0           0
774         1       2    0   54      1      3         2           0
775         0       3    1   18      0      0         2           0
776         0       3    1   28      0      0         1           0
777         1       3    0    5      0      0         2           1
778         0       3    1   28      0      0         1           0
779         1       1    0   43      0      1         2           1
780         1       3    0   13      0      0         0           1
781         1       1    0   17      1      0         2           1
782         0       1    1   29      0      0         2           0
783         0       3    1   28      1      2         2           0
784         0       3    1   25      0      0         2           0
785         0       3    1   25      0      0         2           0
786         1       3    0   18      0      0         2           1
787         0       3    1    8      4      1         1           0
788         1       3    1    1      1      2         2           1
789         0       1    1   46      0      0         0           0
790         0       3    1   28      0      0         1           0
791         0       2    1   16      0      0         2           0
792         0       3    0   28      8      2         2           0
793         0       1    1   28      0      0         0           0
794         0       3    1   25      0      0         2           0
795         0       2    1   39      0      0         2           0
796         1       1    0   49      0      0         2           1
797         1       3    0   31      0      0         2           0
798         0       3    1   30      0      0         0           0
799         0       3    0   30      1      1         2           0
800         0       2    1   34      0      0         2           0
801         1       2    0   31      1      1         2           1
802         1       1    1   11      1      2         2           1
803         1       3    1    0      0      1         0           1
804         1       3    1   27      0      0         2           0
805         0       3    1   31      0      0         2           0
806         0       1    1   39      0      0         2           0
807         0       3    0   18      0      0         2           1
808         0       2    1   39      0      0         2           0
809         1       1    0   33      1      0         2           1
810         0       3    1   26      0      0         2           0
811         0       3    1   39      0      0         2           0
812         0       2    1   35      0      0         2           0
813         0       3    0    6      4      2         2           0
814         0       3    1   30      0      0         2           0
815         0       1    1   28      0      0         2           0
816         0       3    0   23      0      0         2           1
817         0       2    1   31      1      1         0           0
818         0       3    1   43      0      0         2           0
819         0       3    1   10      3      2         2           0
820         1       1    0   52      1      1         2           1
821         1       3    1   27      0      0         2           0
822         0       1    1   38      0      0         2           0
823         1       3    0   27      0      1         2           1
824         0       3    1    2      4      1         2           0
825         0       3    1   28      0      0         1           0
826         0       3    1   28      0      0         2           0
827         1       2    1    1      0      2         0           1
828         1       3    1   28      0      0         1           0
829         1       1    0   62      0      0         2           0
830         1       3    0   15      1      0         0           1
831         1       2    1    0      1      1         2           1
832         0       3    1   28      0      0         0           0
833         0       3    1   23      0      0         2           0
834         0       3    1   18      0      0         2           0
835         1       1    0   39      1      1         0           1
836         0       3    1   21      0      0         2           0
837         0       3    1   28      0      0         2           0
838         1       3    1   32      0      0         2           0
839         1       1    1   28      0      0         0           0
840         0       3    1   20      0      0         2           0
841         0       2    1   16      0      0         2           0
842         1       1    0   30      0      0         0           1
843         0       3    1   34      0      0         0           0
844         0       3    1   17      0      0         2           0
845         0       3    1   42      0      0         2           0
846         0       3    1   28      8      2         2           0
847         0       3    1   35      0      0         0           0
848         0       2    1   28      0      1         2           0
849         1       1    0   28      1      0         0           1
850         0       3    1    4      4      2         2           0
851         0       3    1   74      0      0         2           0
852         0       3    0    9      1      1         0           1
853         1       1    0   16      0      1         2           1
854         0       2    0   44      1      0         2           0
855         1       3    0   18      0      1         2           1
856         1       1    0   45      1      1         2           0
857         1       1    1   51      0      0         2           0
858         1       3    0   24      0      3         0           1
859         0       3    1   28      0      0         0           0
860         0       3    1   41      2      0         2           0
861         0       2    1   21      1      0         2           0
862         1       1    0   48      0      0         2           0
863         0       3    0   28      8      2         2           0
864         0       2    1   24      0      0         2           0
865         1       2    0   42      0      0         2           1
866         1       2    0   27      1      0         0           1
867         0       1    1   31      0      0         2           0
868         0       3    1   28      0      0         2           0
869         1       3    1    4      1      1         2           1
870         0       3    1   26      0      0         2           0
871         1       1    0   47      1      1         2           0
872         0       1    1   33      0      0         2           1
873         0       3    1   47      0      0         2           0
874         1       2    0   28      1      0         0           1
875         1       3    0   15      0      0         0           1
876         0       3    1   20      0      0         2           0
877         0       3    1   19      0      0         2           0
878         0       3    1   28      0      0         2           0
879         1       1    0   56      0      1         0           0
880         1       2    0   25      0      1         2           1
881         0       3    1   33      0      0         2           0
882         0       3    0   22      0      0         2           1
883         0       2    1   28      0      0         2           0
884         0       3    1   25      0      0         2           0
885         0       3    0   39      0      5         1           0
886         0       2    1   27      0      0         2           0
887         1       1    0   19      0      0         2           1
888         0       3    0   28      1      2         2           0
889         1       1    1   26      0      0         0           0
890         0       3    1   32      0      0         1           0

In [35]:
# Saving Prediction into a CSV file
testing_data_prediction.to_csv(r'model_prediction.csv', index=False, header=True)

In [36]:
# Calculating Accuracy
model_accuracy_score = accuracy_score(testing_data_prediction['Survived'], testing_data_prediction['Prediction'])

print("-- Model Accuracy Score: ", end='')
print(round(model_accuracy_score,3))

-- Model Accuracy Score: 0.832

In [37]:
testing_data.Parch.unique()

array([0, 1, 3, 2, 5], dtype=int64)

# Evaluating on Unseen Data (Application Phase)

<div class="alert alert-block alert-info">
    Testing on Unseen Data (realtime/userinput).
</div>

In [43]:
print("-- Take Input --")
pclass_inp   = input("-- Please Enter Pclass (1, 2, 3) :").strip()
sex_inp      = input("-- Please Enter Gender (Male, Female) :").strip()
age_inp      = input("-- Please Enter Age :").strip()
sibsp_inp    = input("-- Please Enter Number of Sibling/Spouse (0, 1, 2, 3) :").strip()
parch_inp    = input("-- Please Enter Number of Parent/Children (0, 1, 2, 3, 5) :").strip()
embarked_inp = input("-- Please Enter Embarked (C, Q, S) :").strip()

-- Take Input --
-- Please Enter Pclass (1, 2, 3) :2
-- Please Enter Gender (Male, Female) :male
-- Please Enter Age :23
-- Please Enter Number of Sibling/Spouse (0, 1, 2, 3) :2
-- Please Enter Number of Parent/Children (0, 1, 2, 3, 5) :1
-- Please Enter Embarked (C, Q, S) :S

In [44]:
# Convert Input into Feature Vector
user_inp = pd.DataFrame({
    'Pclass':   [pclass_inp],
    'Sex':      [sex_inp],
    'Age':      [age_inp],
    'SibSp':    [sibsp_inp],
    'Parch':    [parch_inp],
    'Embarked': [embarked_inp]
})

print("-- User Inputs are: ")
print(user_inp)

-- User Inputs are:
  Pclass   Sex Age SibSp Parch Embarked
0      2  male  23     2     1        S

In [45]:
# Transform Input Into Numerical Representation
user_inp_features = user_inp.copy()

# user_inp_features['Pclass']   = 
user_inp_features['Sex']      = sex_label_encoder.transform(user_inp['Sex'])
# user_inp_features['Age']      = 
# user_inp_features['SibSp']    = 
# user_inp_features['Parch']    = 
user_inp_features['Embarked'] = embarked_label_encoder.transform(user_inp['Embarked'])

print("-- User Input Encodede Feature Vector --")
print(user_inp_features)

-- User Input Encodede Feature Vector --
  Pclass  Sex Age SibSp Parch  Embarked
0      2    1  23     2     1         2

In [46]:
# Loading Saved SVC Model
model = pickle.load(open('model_svc.pkl', 'rb'))

In [47]:
# Prediction on Unseen Data
predicted_survival = model.predict(user_inp_features)
if(predicted_survival == 1):
    prediction = 'Survived'
elif(predicted_survival == 0):
    prediction = 'Not Survived'


print("-- Prediction: ", end='')
print(prediction)

-- Prediction: Not Survived